# Site settings
course_name: Deep Learning
course_description: "Deep Learning has lately become the driving force behind numerous high-performing AI/ML products deployed in
real-world across diverse disciplines. Tech giants such as Google, Microsoft, Facebook, Amazon, etc. have strongly been employing 
the Deep Learning workforce in the past few years for developing various applications in Computer Vision, Natural Processing, etc.
Also, various organizations, such as OpenAI, DeepMind, etc., that intend to work towards developing safe and responsible Artificial General Intelligence (AGI) conduct research in Deep Learning.
Hence, it has recently become one of the most sought-after courses. In this course, we will discuss (with a focus on the implementation) the various
building blocks required to realize the Deep Learning solutions from a simple neuron model to Generative AI."
course_semester: "Jan-May 2025"

baseurl: "/dl25" # the subpath of your site, e.g. /blog/
url: "http://krmopuri.github.io/" # the base hostname & protocol for your site

schoolname: "Dept. of AI, IITH"
schoolurl: "https://ai.iith.ac.in/"
#twitter_username: username 

address: |
    Department of Artificial Intelligence
    IIT Hyderabad, India

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
